---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
#  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[mysql::server]
      - recipe[ya-piwik::default]
    attributes:
      php:
        use_atomic_repo: false
        mysql_module_edition: 'mysql'
      mysql:
        server_root_password: 'secret-password-here'

